config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'

  resources :rutines

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rutine.rb
class Rutine < ApplicationRecord
  belongs_to :user
  validates :exercise, presence: true
  validates :sets, presence: true
  validates :reps, presence: true
          
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rutines
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rutines_controller.rb
class RutinesController < ApplicationController

  before_action :get_id, only: [:show, :update, :edit, :destroy]

  def index
    @rutines = Rutine.all
  end
  
  def new
    @rutine = Rutine.new
  end
  
  def create
    @rutine = Rutine.new get_params
    if @rutine.save
      redirect_to rutine_path(@rutine)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @rutine.update(get_params)
      flash[:success] = "Rutine sucessfully updated.."
      redirect_to rutine_path(@rutine)
    else
      flash[:danger] = "Upss, something went wrong.."
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @rutine.destroy
    flash[:success] = "Rutine Deleted..."
    redirect_to rutines_path
  end

  private

  def get_params
    params.require(:rutine).permit(:exercise, :sets, :reps)
  end

  def get_id
    @rutine = Rutine.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rutines_helper.rb
module RutinesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CaliApp", root_path, class:"navbar-brad", id: "logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'New Rutine', new_rutine_path %></li>
            <li><%= link_to 'See My Rutines', rutines_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaliApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/rutines/_form.html.erb
<%= render 'share/errors', obj: @rutine %>

<%= form_for @rutine do |f| %>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">
      <%= f.label :exercise %>
    </label>
    <div class="col-sm-4">
      <%= f.text_field :exercise, type:"text", class:"form-control", placeholder:"Exercise Name", autofocus: true %>
    </div>
  </div> 

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">
      <%= f.label :sets %>
    </label>
    <div class="col-sm-4">
      <%= f.text_field :sets, type:"number", class:"form-control", placeholder:"Sets" %>
    </div>
  </div> 

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">
      <%= f.label :reps %>
    </label>
    <div class="col-sm-4">
      <%= f.text_field :reps, type:"number", class:"form-control", placeholder:"Reps" %>
    </div>
  </div> 

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.submit 'Save', class:"btn btn-sm btn-success" %>
    </div>
  </div>   


<% end %>

app/views/rutines/edit.html.erb
<h1>Edit Rutine</h1>

<%= render 'rutines/form' %>

app/views/rutines/index.html.erb
<h1>Listing Rutines</h1>
 
<table>
  <tr>
    <th>Exercise</th>
    <th>Sets</th>
    <th>Reps</th>
    <th>Action</th>
  </tr>
 
  <% @rutines.each do |r| %>
    <tr>
      <td><%= r.exercise %></td>
      <td><%= r.sets %></td>
      <td><%= r.reps %></td>
      <td><%= link_to 'Show', rutine_path(r) %> /
        <%= link_to 'Edit', edit_rutine_path(r) %> /
        <%= link_to 'Deleted', rutine_path(r), method: :delete, data: {confirm: "Are you sure ? "} %></td>
    </tr>
  <% end %>
</table>

app/views/rutines/new.html.erb
<h1>Create Rutine</h1>

<%= render 'rutines/form' %>

app/views/rutines/show.html.erb
<p>
  <strong>Exercise:</strong>
  <%= @rutine.exercise %>
</p>
 
<p>
  <strong>Sets:</strong>
  <%= @rutine.sets %>
</p>

<p>
  <strong>Reps:</strong>
  <%= @rutine.reps %>
</p>

app/views/share/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, 'error')%>
            Prohibited this <%= obj.class %> from being save:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>  
        </div>
      </div>  
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Calistechnic  App</h1>
<p></p>